# Generated by Django 5.2.5 on 2025-08-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dispositivo',
            new_name='Dispositivos',
        ),
    ]
